version: "3.5"

services:
  pocketbase:
    build: pocketbase/
    restart: unless-stopped
    ports:
      - "8090:8090"
  svelte-kit:
    build:
      context: kontaktverzeichnis/
      args:
        APIUser: ${APIUser}
        APIPW: ${APIPW}
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file: .env #Benutzt standardmäßig .env im Folder
    depends_on:
      - pocketbase
