version: "3.5"

services:
  svelte-kit:
    build:
      context: kontaktverzeichnis/
      args:
        APIUser: api
        APIPW: yourPassword
        SERVER: pocketbase:8090
    restart: unless-stopped
    #ports:
    #  - "3000:3000"
    #ports:
    #  - "3000:3000"

  ngnix:
    build: nginx/
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
