version: "3.5"

services:
  pocketbase:
    build: pocketbase/
    restart: unless-stopped
    # ports:
    #   - "8090:8090"
  svelte-kit:
    build:
      context: kontaktverzeichnis/
      args:
        APIUser: api
        APIPW: yourPassword
        SERVER: pocketbase:8090
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - pocketbase
  # ngnix:
