version: "3.5"

services:
  svelte-kit:
    env_file:
      - ./kontaktverzeichnis/.env
    build:
      context: kontaktverzeichnis/
      dockerfile: Dockerfile
      args:
        MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
        Prisma_URL: ${Prisma_URL}
        QUERY_BATCH_SIZE: ${QUERY_BATCH_SIZE}
        JWT_Secret: ${JWT_Secret}
        AD_Controller: ${AD_Controller}
        AD_Searchbase: ${AD_Searchbase}
        AD_AccessGroupDN: ${AD_AccessGroupDN}
        PUBLIC_MEILI_SEARCH_KEY: ${PUBLIC_MEILI_SEARCH_KEY}
    depends_on:
      - meilisearch
    restart: unless-stopped

  meilisearch:
    image: getmeili/meilisearch
    restart: unless-stopped
    volumes:
      - ./meilisearch/data:/meili_data
    env_file:
      - ./kontaktverzeichnis/.env
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - MEILI_ENV=${MEILI_ENV}ss
      - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS}
  ngnix:
    build: nginx/
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    depends_on:
      - svelte-kit
      - meilisearch
