version: "3.5"

services:
  svelte-kit:
    build:
      context: kontaktverzeichnis/
      dockerfile: Dockerfile_dev
    restart: unless-stopped
    volumes:
      - ./kontaktverzeichnis:/app
      - /app/node_modules/
    ports:
      - "5173:5173"
    env_file:
      - ./kontaktverzeichnis/.env
    environment:
      - PUBLIC_NODE_ENV=dev
    depends_on:
      - meilisearch

  meilisearch:
    image: getmeili/meilisearch
    restart: unless-stopped
    environment:
      - MEILI_ENV=development
    ports:
      - "7700:7700"
    volumes:
      - ./meilisearch/data:/meili_data
    env_file:
      - ./kontaktverzeichnis/.env
